"""convert role column to string and set default

Revision ID: 8cbc6d017723
Revises: 5957ed742b98
Create Date: 2026-03-30 13:15:20.866569

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cbc6d017723'
down_revision: Union[str, Sequence[str], None] = '5957ed742b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CUSTOMER', 'ADMIN', name='userrole'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###
    op.execute("UPDATE users SET role = LOWER(role);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('CUSTOMER', 'ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
